export const API_CONFIG = {
  TELEGRAM_BOT_TOKEN:process.env.TELEGRAM_TOKEN,
  SUPABASE_URL:process.env.SUPABASE_URL, 
  SUPABASE_KEY:process.env.SUPABASE_KEY, 
  DATABASE_URL:process.env.DATABASE_URL,
  VERCEL_INTEGRATION_CLIENT_ID:process.env.CLIENT_ID,
  VERCEL_INTEGRATION_CLIENT_SECRET: process.env.CLIENT_SECRET
}